### ISSUE TITLE
LinRegPCR version error

### ISSUE THREAD

**Issue by bjbvoesenek** [bjbvoesenek/qPCR-analysis#21]
It appears that different versions of LinRegPCR provide differently organized Excel output files...

This error happened to someone that who used LinRegPCR 2012

I used LinRegPCR 2021.2 (newest version), so we should put this in the manual. If people use other versions, they should check if the excel organization and naming of columns is identical to the example input file. But I would just recommend everyone to use the newest LinRegPCR version

Where in the manual shall we write this? I think in the installation part, but it has to be clear that it is different from the python installation

**Comment by ifokkema** [comment]
This is about the usage, not the installation of the tool. However:
- What is the actual difference between the files?
- Can the Python tool tell the difference?
- If so, can't the Python tool simply:
  - Recognize the version of the input by the structure or the names of the tabs,
  - Parse the result of an older version into the same object structure and/or rename the internal tab or column names to match the new version,
  - Handle the data regardless of the given input version?
- If the Python script can't tell the difference, can we ask the users to provide us with a version, after which Python still handles both files?
- If nothing is possible on our end, we should add it to the manual, indeed, but in the part where we explain how to use the tool.

**Comment by bjbvoesenek** [comment]
Might work indeed, I will check next week! Thanks for the comment!

Can you test the script of branch version2.0.1? It works for me in python, but in anaconda prompt I get an error about qpcr_plots_sorted being too large, while I didn't change anything here. I don't know what causes this, but as the script works perfectly fine in Spyder so it might be an anaconda prompt thing?

**Comment by bjbvoesenek** [comment]
> Can you test the script of branch version2.0.1? It works for me in python, but in anaconda prompt I get an error about qpcr_plots_sorted being too large, while I didn't change anything here. I don't know what causes this, but as the script works perfectly fine in Spyder so it might be an anaconda prompt thing?

Solved, I still don't know why the error only happened in one of the programms, but I just made the subplots smaller so that the total figure will also be smaller

**Comment by bjbvoesenek** [comment]
Yes, it was closed!

**Comment by ifokkema** [comment]
Excellent, thanks! Github will automatically close issues if the relevant PR includes a text like "Closes #21". GitHub then understands that, when the PR is merged, #21 can be closed. It's a great way of cleaning out the issue list automatically.
